baseURL = "https://byron42.github.io/Brian_Efflandt_Portfolio/"
# baseURL = "https://example.com/"

relativeURLs = true

languageCode = "en"
title = "Brian Efflandt Coding Portfolio"
theme = "initio"

# not sure?
canonifyURLs = true

googleAnalytics = "G-S1TRRJ67TF"

[params]
    logo = "images/head-icon.png"
    logoclass = "LOGO"

    button_bg = "images/button_bg.png"
    button_bgclass = "BUTTON"

    info = "images/info/info15.png"

    name = "Brian Efflandt"

    description = "Software Developer"
    email = "efflandt.brian@gmail.com"
    phone = "309.340.4452"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017

    # avatartop = "images/profile_header6.jpg"
    avatar = "images/head-icon.png"

    avatarclass = "circle"
    background = ""
    banner = "images/coding-bg.jpg"
    favicon = "images/head-icon2.png"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    # contact files
    custom_css = ["css/contact.css","css/social.css"]
    custom_js = ["js/social.js","js/content.js"]

    showSubheader = true
    showProjects = true
    showRecentWorks = true  
    showDownloads = false
    showClients = false

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1


# [[menu.main]]
#     name = "contact"
#     url = "/post/"
#     weight = 5
# [[menu.main]]
#     name = "contact"
#     url = "/js/contact.js"
#     weight = 5



[[menu.projects]]
    name = "WEBSITES"
    url = "repos/websites/"
    weight = 2
[[menu.projects]]
    name = "{ JS }"
    url = "repos/javascript/"
    weight = 1
[[menu.projects]]
    name = "JAVA"
    url = "repos/java/"
    weight = 3
[[menu.projects]]
    name = "C#"
    url = "repos/c_sharp/"
    weight = 4


[[menu.projects]]
    name = "PHP"
    url = "repos/php/"
    weight = 5
[[menu.projects]]
    name = "ACCESS"
    url = "repos/access/"
    weight = 6
[[menu.projects]]
    name = "REACT"
    url = "repos/react/"
    weight = 7
[[menu.projects]]
    name = "MISC"
    url = "repos/misc/"
    weight = 8





[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

# [params.google.analytics]
#     trackerID = "G-S1TRRJ67TF"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/brian-efflandt/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/byron42/my-portfolio"
    icon = "fab fa-github"
    footer = true
    sharethis = true
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:efflandt.brian@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = false
    network = "email"
